### ISSUE TITLE
Feedback for “Replicate” - Error Cannot read properties of undefined (reading 'headers')

### ISSUE THREAD

**Issue by brucevang** [vercel-labs/ai#433] opened 2023-08-10 10:17 UTC
I run the example in the documentation and I get this error. 

- error node_modules\.pnpm\next@13.4.13_react-dom@18.2.0_react@18.2.0\node_modules\next\dist\esm\server\future\route-modules\app-route\module.js (211:60) @ headers
- error Cannot read properties of undefined (reading 'headers')
null
- error node_modules\.pnpm\next@13.4.13_react-dom@18.2.0_react@18.2.0\node_modules\next\dist\esm\server\future\route-modules\app-route\module.js (211:60) @ headers
- error Cannot read properties of undefined (reading 'headers')

**Comment by MaxLeiter** [comment] 2023-08-10 15:41
Please provide a repository or more code, this is difficult to work with. Off the top of my head it seems like you might be using `headers()` outside of Next.js.

**Comment by MaxLeiter** [comment] 2023-08-13 21:48
Closing without more information because this can't be reproduced here. 

I found this on google: https://stackoverflow.com/questions/76396471/typeerror-cannot-read-properties-of-undefined-reading-headers-at-eval-next

are you missing a return statement? Please provide some code if you still need assistance.

**Closed by MaxLeiter** 2023-08-13 21:48 UTC

**Comment by brucevang** [comment] 2023-08-14 16:16
I figured it out. The Replicate example on the website is outdated. I used the code in the Git repo and it worked. Thanks for the example!

**Comment by brucevang** [comment] 2023-08-14 18:49
@MaxLeiter Sure, here's the link. https://sdk.vercel.ai/docs/guides/providers/replicate

Docs Site - Two seperate route.ts files.
Latest in Git - One route.ts file.

**Comment by lgrammel** [comment] 2026-07-22 18:54
## Identify issue type

Identified as **Documentation**  
Confidence: **High**

### Rationale
The failure was traced to outdated sample code in the Replicate documentation rather than broken SDK behavior, so this requires a documentation correction.

### Evidence
- The Replicate code shown in the documentation produced a runtime error.
- The reporter confirmed that the current Git repository code worked while the website guide was outdated.
- The linked documentation used two separate `route.ts` files, unlike the working Git version with one file.
