### ISSUE TITLE
error deploying 'Next.js OpenAI Starter' template to Vercel

### ISSUE THREAD

**Issue by nauticuff** [vercel-labs/ai#268] opened 2023-07-03 04:59 UTC
When attempting to deploy this template I receive an error of: error Couldn't find any versions for "ai" that matches "^2.1.14"
![versionerror](https://github.com/vercel-labs/ai/assets/106128827/818d7b57-f45e-4ea4-9fb3-71bc4b95025a)

**Comment by jiarenlim** [comment] 2023-07-03 05:02
i have the same issues when i tried the huggingface starter

**Comment by kitchenbeats** [comment] 2023-07-03 05:52
This is an incorrect version. The highest release version is 2.1.13. I had the same error. I also get a svelte dependency error now with any version of ai past 2.1.9.

**Comment by jaredpalmer** [comment] 2023-07-03 12:50
Looks like a release failed. This is fixed now.

**Closed by jaredpalmer** 2023-07-03 12:50 UTC

**Comment by lgrammel** [comment] 2026-07-22 19:04
## Identify issue type

Identified as **Bug**  
Confidence: **High**

### Rationale
This was a concrete deployment failure caused by a missing package release required by the starter template, rather than a request for new functionality or documentation.

### Evidence
- Deployment failed because the template required `ai@^2.1.14`, but that version was unavailable.
- Another commenter reproduced the issue and noted that the highest published release was 2.1.13.
- A maintainer confirmed that a release had failed and later fixed it.
