### ISSUE TITLE
LangChain stream not updating the 'isLoading' boolean

### ISSUE THREAD

**Issue by raw-brt** [vercel-labs/ai#181] opened 2023-06-21 14:56 UTC
Hi!

I'm building a small PoC with your amazing SDK, and I'm having a little issue with the 'isLoading' flag from the useChat hook. The stream apparently ends, but the isLoading boolean is stuck on true even when the API stops generating a response.

I can chat properly, though.

This is the code for the route:

```
import { CallbackManager } from 'langchain/callbacks'
import { StreamingTextResponse, LangChainStream, Message } from 'ai'
import { ChatOpenAI } from 'langchain/chat_models/openai'
import { AIChatMessage, HumanChatMessage } from 'langchain/schema'
import {
  ChatPromptTemplate,
  HumanMessagePromptTemplate,
  SystemMessagePromptTemplate
} from 'langchain/prompts'
import { LLMChain } from 'langchain/chains'
import { HUMAN_PROMPT, SYSTEM_PROMPT } from '@/app/data/constants'

export const runtime = 'edge'

export async function POST(req: Request) {
  const json = await req.json()
  const { messages } = json

  const { stream, handlers } = LangChainStream()

  const chatPrompt = ChatPromptTemplate.fromPromptMessages([
    SystemMessagePromptTemplate.fromTemplate(SYSTEM_PROMPT),
    HumanMessagePromptTemplate.fromTemplate(HUMAN_PROMPT)
  ])

  const model = new ChatOpenAI({
    openAIApiKey: process.env.OPENAI_API_KEY,
    streaming: true,
    modelName: 'gpt-3.5-turbo',
    temperature: 0.1,
    callbackManager: CallbackManager.fromHandlers(handlers)
  })

  const chain = new LLMChain({ llm: model, prompt: chatPrompt })

  chain
    .call({
      prompt_variable: (messages as Message[]).map(
        m => {
          if (m.role == 'user') return m.content
        },
        (messages as Message[]).map(m =>
          m.role == 'user'
            ? new HumanChatMessage(m.content)
            : new AIChatMessage(m.content)
        )
      )
    })
    .catch(console.error)

  return new StreamingTextResponse(stream)
}
```

Thank you, and congratulations, this is an amazing project!

**Comment by alexyoung23j** [comment] 2023-06-21 18:26
Noticing the same problem.

**Comment by theotarr** [comment] 2023-06-21 20:04
Same here.

**Comment by fjun99** [comment] 2023-06-22 03:48
same, would u please fix it? thanks

**Comment by 0xterrytjw** [comment] 2023-06-22 04:41
Are there any possible workarounds in the meantime?

**Comment by fjun99** [comment] 2023-06-22 05:02
> Are there any possible workarounds in the meantime?

tried  onFinish，not working.

     onFinish: (message) => {
      setIsResponding(false)
      console.log('Chat stream ended with message:', message);
    },

**Comment by gadicc** [comment] 2023-06-22 11:55
This is due to [#97 ("Stream never closes with LangChainStream using postman")](https://github.com/vercel-labs/ai/issues/97) and there are some workarounds there.

**Comment by raw-brt** [comment] 2023-06-22 12:50
This solution highlighted in the issue #97 worked for me:

`
import { StreamingTextResponse, LangChainStream, Message } from 'ai'
import { CallbackManager } from 'langchain/callbacks'
import { ChatOpenAI } from 'langchain/chat_models/openai'
import { AIChatMessage, HumanChatMessage } from 'langchain/schema'

export const runtime = 'edge'

export async function POST(req: Request) {
  const { messages } = await req.json()

  const { stream, handlers } = LangChainStream({
    onStart: async () => console.log('start'),
    // onToken: async token => console.log(token),
    onCompletion: async () => console.log('end')
  })

  const llm = new ChatOpenAI({
    streaming: true,
    callbackManager: CallbackManager.fromHandlers(handlers)
  })

  llm
    .call(
      (messages as Message[]).map(m =>
        m.role == 'user'
          ? new HumanChatMessage(m.content)
          : new AIChatMessage(m.content)
      )
    )
    .catch(console.error)
    .finally(() => {
      // Call handleStreamEnd when the chat or stream ends
      handlers.handleChainEnd()
    })

  return new StreamingTextResponse(stream)
}
`

**Comment by 0xterrytjw** [comment] 2023-06-23 05:14
The above solution worked for me! Yo, thanks a lot @raw-brt!

**Comment by maxlibin** [comment] 2023-06-30 13:23
I am getting this error with vercel build:

```
  34 |     .finally(() => {
> 35 |       handlers.handleChainEnd();
     |                ^
  36 |     });
  37 | 
  38 |   return new StreamingTextResponse(stream);
npm ERR! Lifecycle script `build` failed with error: 
```

**Comment by aranlucas** [comment] 2023-07-03 23:43
This should be fixed by https://github.com/vercel-labs/ai/pull/201

**Comment by MaxLeiter** [comment] 2023-07-03 23:57
Thanks @aranlucas!

**Closed by MaxLeiter** 2023-07-03 23:57 UTC

**Comment by lgrammel** [comment] 2026-07-22 19:12
## Identify issue type

Identified as **Bug**  
Confidence: **High**

### Rationale
This is a concrete failure in existing streaming behavior: the LangChain stream does not close correctly, so `useChat` never resets its loading state.

### Evidence
- `useChat` leaves `isLoading` stuck at `true` after the LangChain response stops generating.
- Multiple commenters reproduced the problem, and a workaround explicitly closes the stream with `handlers.handleChainEnd()`.
- A commenter states that PR #201 should fix the issue.
