### ISSUE TITLE
Prompt engineering example Step 3 not working as intended

### ISSUE THREAD

**Issue by Lukas-Zoellner** [vercel-labs/ai#102] opened 2023-06-16 08:05 UTC
In the prompt engineering docs in [the third step of the example](https://sdk.vercel.ai/docs/concepts/prompt-engineering#tweak-your-settings) readers get encouraged to "re-submit the identical prompt a few times with temperature set to 1." with the intention to produce more varied outcomes due to higher temperatures.
There seems to be an issue (with caching?) here. I'm getting the same response, no matter how often i submit the prompt.

**Comment by wadefletch** [comment] 2023-06-17 00:17
I experienced the same!

**Comment by MaxLeiter** [comment] 2023-08-13 21:41
This was resolved by #445, sorry for missing this. Thanks for the report!

**Closed by MaxLeiter** 2023-08-13 21:41 UTC

**Comment by lgrammel** [comment] 2026-07-22 19:16
## Identify issue type

Identified as **Bug**  
Confidence: **High**

### Rationale
This reports concrete behavior that prevented an existing documented example from working as intended, and the maintainer confirmed it required a fix.

### Evidence
- The prompt-engineering example instructed users to resubmit an identical prompt at temperature 1 to obtain varied responses, but repeated submissions returned the same response.
- Another user reproduced the behavior.
- A maintainer stated that the issue was resolved by PR #445.
