### ISSUE TITLE
Function calling (GPT Update) API updates - June 13th, 2023

### ISSUE THREAD

**Issue by lautapercuspain** [vercel-labs/ai#185] opened 2023-06-21 16:23 UTC
Hey folks,  as you may know, Open AI introduced 2 new params and a different response, which may not be using streams.  

Are we considering giving support for these new params: `functions` and `function_call `  in the `useChat` hook ?

I know we have the extra body param to already send these extra params but, correct me if am wrong here, we don't have yet, a response parsing support for it. 

I would love to hear your thoughts.

**Comment by MaxLeiter** [comment] 2023-06-22 23:53
Thanks for your interest here and in the PR, @lautapercuspain! I'm going to close this issue as a dupe of #80

**Closed by MaxLeiter** 2023-06-22 23:53 UTC

**Comment by lautapercuspain** [comment] 2023-06-23 02:18
> Thanks for your interest here and in the PR, @lautapercuspain! I'm going to close this issue as a dupe of #80

@MaxLeiter, I did't see #80 before. Thank you!

**Comment by lgrammel** [comment] 2026-07-22 19:11
## Identify issue type

Identified as **None**  
Confidence: **High**

### Rationale
Although the original post requests new API support, the issue is primarily duplicate bookkeeping and was explicitly closed as such, so it is classified as none.

### Evidence
- The issue asks whether `useChat` will support OpenAI's new `functions` and `function_call` parameters and response parsing.
- A maintainer closed it as a duplicate of issue #80, and the reporter acknowledged the duplicate.
