### ISSUE TITLE
How to confirm `onFinish` is functioning correctly?

### ISSUE THREAD

**Issue by aerinkim** [vercel-labs/ai#376] opened 2023-07-22 15:58 UTC
Hi, I was following rather a complex tutorial https://github.com/tierrun/tier-vercel-openai/blob/main/src/components/app/GenerateSection.tsx but couldn't confirm if the `onFinish` is working as expected.
So now I'm doing a simple logging check using `onFinish`.

```  

const {
    completion,
    setCompletion,
    input,
    setInput,
    isLoading,
    handleInputChange,
    handleSubmit,
  } = useCompletion({
    api: "/api/generate2",
    body: {
      model: "gpt-4",
    },
    onFinish: (input: string, completion: string) => {
        console.log(`input: ${input}, completion: ${completion}`);
  }});
```

The code above successfully generates the `completion` and I can render it through html, however, even after the completion, this simple console.log using `onFinish` isn't working.

Can someone point out how to verify `onFinish` is actually working?

**Comment by MaxLeiter** [comment] 2023-07-22 19:25
Are you on `ai@2.1.25`? I'm unable to reproduce locally:

```
  const { completion, input, handleInputChange, handleSubmit } = useCompletion({
    api: '/api/completion',
    onFinish(prompt, completion) {
        console.log("onFinish", prompt, completion);
    },
    onResponse(response) {
        console.log("onResponse", response);
    },
  });
```

```
onResponse Response { type: "basic", url: "http://localhost:3000/api/completion", redirected: false, status: 200, ok: true, statusText: "OK", headers: Headers(6), body: ReadableStream, bodyUsed: false }

onFinish testing # Shopbot
```

**Comment by MaxLeiter** [comment] 2023-07-25 19:16
hey @aerinkim, I'm going to close this due to being unable to reproduce. Please let us know if it's still a problem!

**Closed by MaxLeiter** 2023-07-25 19:16 UTC

**Comment by ZainAli104** [comment] 2024-06-09 09:46
> hey @aerinkim, I'm going to close this due to being unable to reproduce. Please let us know if it's still a problem!

I am also getting the same error that onFinish function don't work expectedly

**Comment by ZainAli104** [comment] 2024-06-11 13:50
In the above version of this ^1.31.3. onFinish callback function mark as deprecated and now what is alternative of this?

**Comment by lgrammel** [comment] 2026-07-22 18:58
## Identify issue type

Identified as **None**  
Confidence: **Medium**

### Rationale
This is primarily a support question with an unverified failure. Since maintainers could not reproduce it and no concrete reproduction established broken SDK behavior, it is not confidently classifiable as a bug.

### Evidence
- Reporter asks how to verify an `onFinish` callback that did not log despite completion succeeding.
- Maintainer tested `ai@2.1.25`, confirmed `onFinish` worked, and requested a full reproduction, which was not provided.
- A later commenter reported similar behavior and asked for an alternative to a deprecated callback, but provided no reproducible case.
