### ISSUE TITLE
Getting 'undefined' response in nodejs implementation of the sdk

### ISSUE THREAD

**Issue by Aishikboy109** [vercel-labs/ai#132] opened 2023-06-17 11:39 UTC
when I am running this code : 

```

const h = require('@huggingface/inference')

const Hf = new h.HfInference(process.env.HUGGINGFACE_API_KEY)


// Request the HuggingFace API for the response
async function start() {
  const response = await Hf.textGenerationStream({
    model: 'oasst-sft-4-pythia-12b-epoch-3.5',
    inputs: "Hello",
    parameters: {
      max_new_tokens: 200,
      // @ts-expect-error -- The HfInference API doesn't have types for `typical_p` even though it's necessary
      typical_p: 0.2,
      repetition_penalty: 1,
      truncate: 1000,
    },
  })

  const completion = response.generated_text
  console.log(completion)
}

start()

```

The output is `undefined`. What is wrong here?

**Comment by shuding** [comment] 2023-06-17 12:04
Can you check what `response` is? There might be some error message attached.

**Comment by karlbateman** [comment] 2023-06-18 13:02
Running the following:

```javascript
const h = require('@huggingface/inference');

const Hf = new h.HfInference(process.env.HUGGINGFACE_API_KEY);

// Request the HuggingFace API for the response
async function start() {
  const response = Hf.textGenerationStream({
    model: 'oasst-sft-4-pythia-12b-epoch-3.5',
    inputs: 'Hello',
    parameters: {
      max_new_tokens: 200,
      typical_p: 0.2,
      repetition_penalty: 1,
      truncate: 1000,
    },
  });

  console.log('Response: ', response);
  const completion = response.generated_text;
  console.log('Completion: ', completion);
}

start();
```

Outputs:

```text
Response:  Object [AsyncGenerator] {}
Completion:  undefined
```

**Comment by shuding** [comment] 2023-06-18 15:39
As you can see, `response.generated_text` is not defined. Where did you find the code of `response.generated_text` in the docs?

We have an example [here](https://sdk.vercel.ai/docs/guides/huggingface) here that shows how the SDK should be used:

![CleanShot-2023-06-18-OFBh3yE5@2x](https://github.com/vercel-labs/ai/assets/3676859/7d151bb3-2bbe-4b63-bc09-67b5b5921613)

**Comment by karlbateman** [comment] 2023-06-18 16:21
I'm trying to debug an issue with the example you've shared which is [documented]. At first my implementation was working but after a few interactions I am no longer getting results.

[documented]: https://sdk.vercel.ai/docs/guides/huggingface

My investigation brought me to this issue in which I'd thought the source was with the API reponse, however I have been unable to debug where the problem occurs.

First thought was perhaps there is an issue with the streams not being closed which is exacerbated when NextJS restarts the dev server on code change. I'm currently unable to confirm this and as there are so many moving parts, I fear this may take some time to debug.

In the meantime, I have fallen back to using the OpenAI integration which has been easier to setup.

Absolutely love the project and the work that has gone into streamlining the integrations ❤️ I'm excited to see where this project goes.

**Comment by shuding** [comment] 2023-06-21 15:22
Thank you! Feel free to open an issue or discussion whenever you're running into a problem again. I'll close this for now as there's nothing to track at the moment.

**Closed by shuding** 2023-06-21 15:22 UTC
Labels: reproduction needed

**Comment by hypnocill** [comment] 2023-10-26 20:48
@karlbateman did you find what was the issue? I encounter the same situation in which it just stops working and I can't error handle it. Code change hot reloading came to my mind too but can't confirm it

**Comment by lgrammel** [comment] 2026-07-22 19:15
## Identify issue type

Identified as **None**  
Confidence: **High**

### Rationale
This is primarily a usage/debugging question involving an unconsumed async stream, followed by an unconfirmed intermittent problem. No concrete AI SDK defect was established.

### Evidence
- `textGenerationStream()` returns an `AsyncGenerator`, so reading `response.generated_text` directly yields `undefined`.
- The maintainer pointed to the documented streaming integration rather than identifying an SDK defect.
- A later report of the documented example intermittently stopping was not reproducible or isolated, and the maintainer closed the issue because there was nothing actionable to track.
