### ISSUE TITLE
No matching version found for ai@2.0.1.

### ISSUE THREAD

**Issue by esponges** [vercel-labs/ai#82] opened 2023-06-15 22:13 UTC
All the projects located in https://github.com/vercel-labs/ai/tree/main/examples have the version `2.0.1` in `package.json`.

This version can't by found by the registry. 

However `2.0.0` works perfectly fine.

```
next-langchain git:(main) ✗ npm i
npm ERR! code ETARGET
npm ERR! notarget No matching version found for ai@2.0.1.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/fertostado/.npm/_logs/2023-06-15T21_57_28_736Z-debug-0.log
➜  next-langchain git:(main) ✗ yarn install
yarn install v1.22.19
info No lockfile found.
[1/4] 🔍  Resolving packages...
Couldn't find any versions for "ai" that matches "2.0.1"
? Please choose a version of "ai" from this list: 2.0.0
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
warning "ai > sswr@1.10.0" has unmet peer dependency "svelte@^3.29.0".
[4/4] 🔨  Building fresh packages...

success Saved lockfile.
✨  Done in 15.89s.
```

Fix proposed in #81

**Comment by MaxLeiter** [comment] 2023-06-15 22:23
Fixed with #83

**Closed by MaxLeiter** 2023-06-15 22:23 UTC

**Comment by JackHowa** [comment] 2023-06-16 14:30
Still getting this for the next.js and open ai starter 

```
yarn install v1.22.17
--
09:27:42.011 | info No lockfile found.
09:27:42.015 | [1/4] Resolving packages...
09:27:44.822 | error Couldn't find any versions for "ai" that matches "2.1.1"
09:27:44.822 | info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
09:27:44.842 | Error: Command "yarn install" exited with 1
09:27:45.232 | BUILD_UTILS_SPAWN_1: Command "yarn install" exited with 1
```

**Comment by lgrammel** [comment] 2026-07-22 19:18
## Identify issue type

Identified as **Examples**  
Confidence: **High**

### Rationale
The failure is caused by invalid dependency versions in runnable example projects and starters, so it is an examples issue rather than broken AI SDK runtime behavior.

### Evidence
- Example projects referenced unpublished package versions such as `ai@2.0.1`, causing `npm install` and `yarn install` to fail.
- A commenter reported the Next.js/OpenAI starter still referenced unavailable `ai@2.1.1` after an attempted fix.
- The issue was addressed through changes to the affected examples/starter dependencies.
