### ISSUE TITLE
Append completion instead of wiping it when triggering a new complete()

### ISSUE THREAD

**Issue by someguy9** [vercel-labs/ai#323] opened 2023-07-12 22:31 UTC
Is there a way to append completion when using useCompletion() rather than reset it when submitting via complete(). initialCompletion could work for this but there is no way to reference the initial content.

**Comment by MaxLeiter** [comment] 2023-07-13 02:12
Going to close as a dupe of #167. PRs welcome!

**Closed by MaxLeiter** 2023-07-13 02:12 UTC

**Comment by lgrammel** [comment] 2026-07-22 19:00
## Identify issue type

Identified as **Feature**  
Confidence: **High**

### Rationale
This requests an additional append behavior for `useCompletion`, rather than reporting a failure of documented behavior. Duplicate status does not change the underlying request from an enhancement.

### Evidence
- The current `useCompletion().complete()` behavior resets the completion, while the reporter wants an option to append to it.
- The maintainer identifies it as a duplicate of #167 and welcomes pull requests, indicating the capability is not currently available.
