### ISSUE TITLE
ERESOLVE could not resolve error revolving around Svelte

### ISSUE THREAD

**Issue by glamboyosa** [vercel-labs/ai#296] opened 2023-07-07 14:20 UTC
Installing `ai` works fine (using npm) but when you want to install something else, you get this error: 
```bash 
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR! 
npm ERR! While resolving: ai@2.1.15
npm ERR! Found: svelte@3.59.2
npm ERR! node_modules/svelte
npm ERR!   peer svelte@"^3.29.0" from sswr@1.10.0
npm ERR!   node_modules/sswr
npm ERR!     sswr@"^1.10.0" from ai@2.1.15
npm ERR!     node_modules/ai
npm ERR!       ai@"^2.1.15" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peerOptional svelte@"^4.0.0" from ai@2.1.15
npm ERR! node_modules/ai
npm ERR!   ai@"^2.1.15" from the root project
npm ERR! 
npm ERR! Conflicting peer dependency: svelte@4.0.5
npm ERR! node_modules/svelte
npm ERR!   peerOptional svelte@"^4.0.0" from ai@2.1.15
npm ERR!   node_modules/ai
npm ERR!     ai@"^2.1.15" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /Users/osa/.npm/eresolve-report.txt for a full report.

```

basically seems two different Svelte versions are clashing. 

running npm install ai with either args i.e. `--force` or `--legacy-peer-deps` works. 

Solution is to uninstall then install it after. 

Node version: `v18.10.0` 
NPM version: `8.19.2`

**Comment by shuding** [comment] 2023-07-07 14:36
Thanks! We should change the version here to be `^3.0.0 || ^4.0.0` as `sswr` uses 3.x:

https://github.com/vercel-labs/ai/blob/e86c2ecc1a810626167bfe5a827f7da1d14889c8/packages/core/package.json#L80

**Comment by swiecki** [comment] 2023-07-07 20:06
just wanted to point out the temporary fix to anyone facing this:

in your package.json you can add

``` javascript
 "overrides": {
    "ai": {
      "svelte": "^3.0.0 || ^4.0.0"
    }
  }
```

**Comment by MaxLeiter** [comment] 2023-07-07 21:26
This should be resolved in the most recent release

**Comment by MaxLeiter** [comment] 2023-07-07 21:26
```
~/D/ai-sdk/e/sveltekit-openai main ❱ pnpm i
Scope: all 10 workspace projects
../.. prepare$ husky install
│ husky - Git hooks installed
└─ Done in 325ms
../nuxt-openai postinstall$ nuxt prepare
│ Nuxi 3.5.3
│ [nuxt:tailwindcss] ℹ Using default Tailwind CSS file
│ ✔ Types generated in .nuxt
└─ Done in 1.6s
../nuxt-langchain postinstall$ nuxt prepare
│ Nuxi 3.5.3
│ [nuxt:tailwindcss] ℹ Using default Tailwind CSS file
│ ✔ Types generated in .nuxt
└─ Done in 1.6s
Done in 3.1s
```

**Closed by MaxLeiter** 2023-07-07 21:26 UTC

**Comment by lgrammel** [comment] 2026-07-22 19:02
## Identify issue type

Identified as **Bug**  
Confidence: **High**

### Rationale
This is a concrete dependency-resolution failure caused by an incorrect Svelte peer dependency range in an existing release, and maintainers confirmed and fixed it.

### Evidence
- Installing another package after `ai@2.1.15` fails with npm `ERESOLVE` because `ai` requires optional peer `svelte@^4.0.0` while its `sswr` dependency uses Svelte 3.x.
- A maintainer confirmed the peer range should be changed to `^3.0.0 || ^4.0.0`.
- A later maintainer comment states the conflict was resolved in the most recent release.
