### ISSUE TITLE
Request to have token count in messages

### ISSUE THREAD

**Issue by tuffstuff9** [vercel-labs/ai#339] opened 2023-07-16 13:12 UTC
Currently, the messages are returned with 'content', 'id', and 'role'. It would be useful to also have 'tokens' and 'cumulative_tokens' with each message.

**Comment by MaxLeiter** [comment] 2023-07-16 18:32
Dupe of #85. I have some ideas on how to accomplish this 👍

**Closed by MaxLeiter** 2023-07-16 18:32 UTC

**Comment by lgrammel** [comment] 2026-07-22 18:59
## Identify issue type

Identified as **Feature**  
Confidence: **High**

### Rationale
This requests a new token-counting capability in returned messages. Although marked as a duplicate, its substantive issue type is a feature request.

### Evidence
- The requester proposes adding `tokens` and `cumulative_tokens` fields to each returned message.
- No existing documented behavior is described as broken.
- A maintainer identifies the request as a duplicate of #85 and notes possible implementation ideas.
