### ISSUE TITLE
LangChain usage issue.

### ISSUE THREAD

**Issue by tnguye20** [vercel-labs/ai#173] opened 2023-06-20 16:23 UTC
Ran into this issue while following the LangChain example and guide page. Any clarification or support would be much appreciated.

```
./node_modules/@dqbd/tiktoken/tiktoken_bg.wasm
Module parse failed: Unexpected character '' (1:0)
The module seem to be a WebAssembly module, but module is not flagged as WebAssembly module for webpack.
BREAKING CHANGE: Since webpack 5 WebAssembly is not enabled by default and flagged as experimental feature.
You need to enable one of the WebAssembly experiments via 'experiments.asyncWebAssembly: true' (based on async modules) or 'experiments.syncWebAssembly: true' (like webpack 4, deprecated).
For files that transpile to WebAssembly, make sure to set the module type in the 'module.rules' section of the config (e. g. 'type: "webassembly/async"').
(Source code omitted for this binary file)

Import trace for requested module:
./node_modules/@dqbd/tiktoken/tiktoken_bg.wasm
./node_modules/@dqbd/tiktoken/tiktoken.js
./node_modules/langchain/dist/base_language/count_tokens.js
./node_modules/langchain/dist/llms/openai.js
./node_modules/langchain/dist/index.js
./node_modules/langchain/index.js
```

**Comment by jaredpalmer** [comment] 2023-06-20 18:49
What version of langchain are you on? Old versions required modifying next.config.js to allow WASM support in order for tiktoken to work.

**Comment by MaxLeiter** [comment] 2023-06-22 19:11
Closing without more info / a reproduction. @tnguye20 please reply back if you haven't been able to solve this by upgrading langchain.

**Closed by MaxLeiter** 2023-06-22 19:11 UTC

**Comment by lgrammel** [comment] 2026-07-22 19:12
## Identify issue type

Identified as **None**  
Confidence: **High**

### Rationale
This is primarily an unresolved support request involving a likely outdated LangChain dependency, without enough information to establish a bug in the AI SDK or its examples.

### Evidence
- Reporter encountered a webpack WebAssembly parsing error while following the LangChain example and asked for clarification or support.
- Maintainer indicated that older LangChain versions required WASM configuration and suggested upgrading.
- The issue was closed because no version details or reproduction were provided, with no confirmed AI SDK defect.
